spring:
  application:
    name: translateservice
  profiles:
    active: dev

logging:
  file: /home/servlets/logs/${spring.application.name}/${spring.application.name}.log
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
  level:
    root: info
    com.mobvoi.onebox: debug

translation:
  stream:
    url: "ws://streaming/websocket/asr?is_oversea=false"
  history:
    saveUrl: "http://gondar/widget/msg/record"
  azure:
    speech-translate-config: '{
    "speech_recognition_url": "https://eastasia.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1", 
    "supported_languages": [
        {
            "name": "普通话", 
            "detail": [
                "zh-CN", 
                "Chinese-simplified"
            ]
        }, 
        {
            "name": "粤语", 
            "detail": [
                "zh-HK", 
                "Chinese-Traditional"
            ]
        }, 
        {
            "name": "英语", 
            "detail": [
                "en-US", 
                "English"
            ]
        }, 
        {
            "name": "日语", 
            "detail": [
                "ja-JP", 
                "Japanese"
            ]
        }, 
        {
            "name": "韩语", 
            "detail": [
                "ko-KR", 
                "Korean"
            ]
        }, 
        {
            "name": "法语", 
            "detail": [
                "fi-FI", 
                "Finnish"
            ]
        }, 
        {
            "name": "德语", 
            "detail": [
                "de-DE", 
                "German"
            ]
        }, 
        {
            "name": "阿拉伯语", 
            "detail": [
                "ar-EG", 
                "Arabic"
            ]
        }
    ], 
    "subscriptionKey": "f9dabe6f0ed54913ba95ce6e3f06bb53"
}'
