translation:
  stream:
    url: "ws://uc-test:8064/streaming-server/websocket/asr?is_oversea=false"
    asr-url: "ws://uc-test:8064/streaming-server/websocket/asr?is_oversea=false"
  history:
    #save-url: "http://gondar.ekswaizei.xyz/widget/msg/record"
    save-url: "http://10.1.196.51:8085/widget/msg/record"

spring:
  cloud:
    config:
      uri: http://localhost:8489
      enabled: true
  redis:
      database: 0
      host: "localhost"
      port: 6379
      password: ""
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
        timeout: 0


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8490/eureka/

