spring:
  profiles: 
    active: pro
---
spring:
  profiles: pro
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
myinfo:
  name : lihao
testinfo:
  name : xrr